import { neon } from "@neondatabase/serverless";

/** Neon uses DATABASE_URL, unless the Vercel integration kept its STORAGE prefix. */
function connectionString() {
  const url = process.env.DATABASE_URL ?? process.env.STORAGE_URL;
  if (!url) {
    throw new Error("Database is not configured. Add DATABASE_URL (or STORAGE_URL) to this environment.");
  }
  return url;
}

export function getSql() {
  return neon(connectionString());
}

let initialization: Promise<void> | undefined;

/** Creates Boardy's schema. It is safe to call from every server route. */
export function initializeDatabase() {
  if (!initialization) {
    initialization = (async () => {
      const sql = getSql();
      await sql`
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL, initials TEXT NOT NULL, role TEXT NOT NULL, department TEXT NOT NULL,
          start_date TEXT NOT NULL, remaining INTEGER NOT NULL DEFAULT 60, score INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Needs support', color TEXT NOT NULL DEFAULT '#e2e8f0',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `;
      await sql`
        CREATE TABLE IF NOT EXISTS event_logs (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL REFERENCES users(id), event_type TEXT NOT NULL, description TEXT NOT NULL,
          payload TEXT NOT NULL DEFAULT '{}', timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          source TEXT NOT NULL DEFAULT 'manual', external_id TEXT
        )
      `;
      await sql`
        CREATE TABLE IF NOT EXISTS summaries (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL REFERENCES users(id), role TEXT NOT NULL, content TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `;
      await sql`
        CREATE UNIQUE INDEX IF NOT EXISTS idx_event_logs_source_external_id
        ON event_logs(source, external_id) WHERE external_id IS NOT NULL
      `;
    })().catch((error) => {
      initialization = undefined;
      throw error;
    });
  }
  return initialization;
}

// ─── Helper Types ───
export type User = {
  id: number;
  name: string;
  initials: string;
  role: string;
  department: string;
  start_date: string;
  remaining: number;
  score: number;
  status: string;
  color: string;
  created_at: string;
};

export type EventLog = {
  id: number;
  user_id: number;
  event_type: string;
  description: string;
  payload: string;
  timestamp: string;
  source: string;
  external_id: string | null;
};

export type Summary = {
  id: number;
  user_id: number;
  role: string;
  content: string;
  created_at: string;
};
